version: "3.3"

services:

  api:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000    
    depends_on:
      - mongo
      - nats
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"

  v1_account:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: account
    depends_on:
      - mysql
      - nats
      - redis
    restart: unless-stopped

  v1_area:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: area
    depends_on:
      - mysql
      - nats
      - redis
    restart: unless-stopped

  v1_city:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: city
    depends_on:
      - mysql
      - nats
      - redis
    restart: unless-stopped

  v1_country:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: country
    depends_on:
      - mysql
      - nats
      - redis
    restart: unless-stopped

  v1_mail:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: mail
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped

  v1_permission:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: permission
    depends_on:
      - mysql
      - nats
      - redis
    restart: unless-stopped

  v1_role:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: role
    depends_on:
      - mysql
      - nats
      - redis
    restart: unless-stopped

  v1_rolepermission:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: rolepermission
    depends_on:
      - mongo
      - nats
      - redis
    restart: unless-stopped

  v1_token:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: token
    depends_on:
      - mysql
      - nats
      - redis
    restart: unless-stopped

  v1_auth:
    build:
      context: .
    image: moleculer-typescript
    env_file: docker-compose.env
    environment:
      SERVICES: auth
    depends_on:
      - mysql
      - nats
      - redis
    restart: unless-stopped

  nats:
    image: nats:2
    networks:
      - internal

  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:

volumes:
  data:
